services:
  backend:
    build:
      context: . # Now relative to backend folder
      dockerfile: Dockerfile
    container_name: component_hub_backend
    ports:
      # Map localhost 8500 to container's 3000
      - "8500:8500"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Persist uploaded files across container restarts
      - backend_uploads:/app/public/uploads

volumes:
  backend_uploads:
